duoclieu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DuocLieuHoc, name='duoc-lieu-hoc'),
    path('ho-thuc-vat/', views.HoThucVatListView. as_view(), name='ho-thuc-vat'),
    path('ho-thuc-vat/<slug:slug>', views.HoThucVatDetailView.as_view(), name='hothucvat-detail'),
    path('duoc-lieu/', views.DuocLieuListView.as_view(), name='duoclieu'),
    path('duoc-lieu/<slug:slug>', views.DuocLieuDetailView.as_view(), name='duoclieu-detail'),
    path('giao-trinh/', views.Level0ListView.as_view(), name='level0'),
    path('giao-trinh/<slug:slug>', views.Level0DetailView.as_view(), name='level0-detail'),
]

hoa_ly/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HoaLy, name='hoa-ly'),
    path('giao-trinh/', views.Level0ListView.as_view(), name='hl-level0'),
    path('giao-trinh/<slug:slug>', views.Level0DetailView.as_view(), name='hl-level0-detail'),
]

thucvat/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.staticfiles.storage import staticfiles_storage


urlpatterns = [
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name = 'signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('duoc-lieu-hoc/', include('duoclieu.urls')),
    path('doc-chat-hoc/', include('doc_chat_hoc.urls')),
    path('duoc-lam-sang/', include('duoc_lam_sang.urls')),
    path('duoc-ly/', include('duoc_ly.urls')),
    path('hoa-duoc/', include('hoa_duoc.urls')),
    path('kiem-nghiem/', include('kiem_nghiem.urls')),
    path('cong-nghiep-duoc/', include('cong_nghiep_duoc.urls')),
    path('phap-che-duoc/', include('phap_che_duoc.urls')),
    path('hoa-ly/', include('hoa_ly.urls')),
    path('sinh-hoa/', include('sinh_hoa.urls')),
    path('cong-nghe-sinh-hoc/', include('cong_nghe_sinh_hoc.urls')),
    path('', RedirectView.as_view(url='home/', permanent=False)),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

duoclieu/models.py
from django.db import models
from django.urls import reverse
from datetime import date, datetime
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

#------------------------------------------------------------------
class LoiNoiDauDL(models.Model):
    loi_noi_dau = models.TextField(max_length = 5000, verbose_name = 'Lời nói đầu', null = True, blank = True, help_text = 'Mỗi "+Add" là một đoạn trong lời nói đầu. Hãy nhập những lời tâm huyết của bạn vào đây vì đây là phần người đọc sẽ thấy đầu tiên khi chọn khối kiến thức dược liệu.')

    class Meta:
       verbose_name = 'Lời nói đầu'
       verbose_name_plural = '0. Lời nói đầu'
       ordering = ['id']

    def __str__(self):
        return f'Đoạn {self.id}'
#------------------------------------------------------------------

class HoThucVat(models.Model):
    La_tinh = models.CharField(max_length = 200, verbose_name ='họ latinh')
    Tieng_viet = models.CharField(max_length = 200, verbose_name = 'họ tiếng việt')
    ngay_dang = models.DateTimeField(auto_now=True, null=True, blank = True, verbose_name ='Ngày cập nhật')
    nguoi_dang = models.CharField(max_length = 200, null = True, blank = True, verbose_name ='người đăng', help_text = 'Tên tác giả, nếu không nhập thông tin chương trình sẽ mặc định là họ và tên của chủ tài khoản (thông tin khai báo lúc đăng ký tài khoản / tạo bởi admin).')
    gioi_thieu_chung = models.TextField(max_length = 1000, verbose_name = 'giới thiện chung', null = True, blank = True, help_text = 'Nếu không có gì để viết vào có thể để trống.')
    slug = models.SlugField(null=True, unique=True, help_text = 'Thông tin này sẽ hiển thị tại địa chỉ web, ví dụ: www.home/ho-thuc-vat/XXXXX, nếu không nhập dữ liệu chương trình sẽ mặc định XXXXX là họ dược liệu.')

    class Meta:
       verbose_name = 'Họ thực vật'
       verbose_name_plural = 'A. Họ thực vật'
       ordering = ['Tieng_viet']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.La_tinh)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.Tieng_viet} ({self.La_tinh})'

    def get_absolute_url(self):
        return reverse('hothucvat-detail', kwargs={'slug': self.slug})


#------------------------------------------------------------------
class DuocLieu(models.Model):
    ten_tieng_viet = models.CharField(max_length = 200, verbose_name ='Tên tiếng việt')
    ten_la_tinh = models.CharField(max_length = 200, verbose_name ='Tên Latinh')
    ho_thuc_vat = models.ForeignKey('HoThucVat', on_delete = models.CASCADE, verbose_name ='Họ thực vật',  help_text ='Kéo chọn họ thực vật phù hợp, nếu họ thực vật chưa có ấn vào dấu + để tạo mới.')
    ngay_dang = models.DateTimeField(auto_now=True, null=True, blank = True, verbose_name ='Ngày cập nhật')
    nguoi_dang = models.CharField(max_length = 200, null = True, blank = True, verbose_name ='người đăng', help_text = 'Tên tác giả, nếu không nhập thông tin chương trình sẽ mặc định là họ và tên của chủ tài khoản (thông tin khai báo lúc đăng ký tài khoản / tạo bởi admin).')
    slug = models.SlugField(null=True, blank=True, unique=True, help_text = 'Thông tin này sẽ hiển thị tại địa chỉ web, ví dụ: www.home/duoclieu/XXXXX, nếu không nhập dữ liệu chương trình sẽ mặc định XXXXX là tên khoa học của dược liệu.')

    class Meta:
        verbose_name = 'Dược liệu'
        verbose_name_plural = 'B. Dược liệu'
        ordering = ['ten_tieng_viet']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.ten_la_tinh)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.ten_tieng_viet} ({self.ten_la_tinh})'

    def get_absolute_url(self):
        return reverse('duoclieu-detail', kwargs={'slug': self.slug})
#------------------------------------------------------------------
class TenKhoaHoc(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    ten_tieng_viet_spp = models.CharField(max_length = 200, verbose_name = 'tên tiếng việt spp', null = True, blank = True)
    ten_latinh_spp = models.CharField(max_length = 200, verbose_name = 'tên latinh spp', null = True, blank = True)

    class Meta:
       verbose_name = 'tên khoa học spp'
       verbose_name_plural = 'tên khoa học spp'

class DacDiemVaPhanBo(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    dac_diem_va_phan_bo = models.TextField(max_length = 1000, verbose_name = 'đặc điểm và phân bố')

    class Meta:
       verbose_name = 'đặc điểm và phân bố'
       verbose_name_plural = 'đặc điểm và phân bố'

class BoPhanDung(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    bo_phan_dung = models.TextField(max_length = 1000, verbose_name = 'bộ phận dùng')

    class Meta:
       verbose_name = 'bộ phận dùng'
       verbose_name_plural = 'bộ phận dùng'

class DacDiemViPhauVaBot(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    dac_diem_vi_phau_va_bot = models.TextField(max_length = 1000, verbose_name = 'đặc điểm vi phẫu và bột')

    class Meta:
       verbose_name = 'đặc điểm vi phẫu và bột'
       verbose_name_plural = 'đặc điểm vi phẫu và bột'

class TacDungVaCongDung(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    tac_dung_va_cong_dung = models.TextField(max_length = 1000, verbose_name = 'tác dụng và công dụng')

    class Meta:
       verbose_name = 'tác dụng và công dụng'
       verbose_name_plural = 'tác dụng và công dụng'

class CheBien(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    che_bien = models.TextField(max_length = 1000, verbose_name = 'chế biến')

    class Meta:
       verbose_name = 'chế biến'
       verbose_name_plural = 'chế biến'

class ChePham(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    che_pham = models.TextField(max_length = 1000, verbose_name = 'chế phẩm')

    class Meta:
       verbose_name = 'chế phẩm'
       verbose_name_plural = 'chế phẩm'

class ChuY(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    chu_y = models.TextField(max_length = 1000, verbose_name = 'chú ý')

    class Meta:
       verbose_name = 'chú ý'
       verbose_name_plural = 'chú ý'

class GhiChu(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    ghi_chu = models.TextField(max_length = 1000, verbose_name = 'ghi chú')

    class Meta:
       verbose_name = 'ghi chú'
       verbose_name_plural = 'ghi chú'

class HinhAnhMinhHoa(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    hinh_anh_minh_hoa = models.ImageField(upload_to='duoclieu', verbose_name = 'hình ảnh minh hoạ')

    class Meta:
       verbose_name = 'hình ảnh minh hoạ'
       verbose_name_plural = 'hình ảnh minh hoạ'

class HinhAnhBoSung(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    hinh_anh_bo_sung = models.ImageField(upload_to='duoclieu', verbose_name = 'hình ảnh bổ sung')

    class Meta:
       verbose_name = 'hình ảnh bổ sung'
       verbose_name_plural = 'hình ảnh bổ sung'

class ThanhPhanHoaHoc(models.Model):
    duoc_lieu = models.ForeignKey('DuocLieu', on_delete = models.CASCADE, verbose_name = 'dược liệu')
    thanh_phan_hoa_hoc = models.TextField(max_length = 1000, verbose_name = 'thành phần hoá học')

    class Meta:
       verbose_name = 'thành phần hoá học'
       verbose_name_plural = 'thành phần hoá học'

#------------------------------------------------------------------
#------------------------------------------------------------------
class Level0(models.Model):
    tieu_de_chinh = models.CharField(max_length = 200, verbose_name = 'tiêu đề chính')
    noi_dung = models.TextField(max_length = 5000, verbose_name = 'mục tiêu', null=True, blank = True)
    nguoi_dang = models.CharField(max_length = 200, null = True, blank = True, verbose_name ='người đăng', help_text = 'Tên tác giả, nếu không nhập thông tin chương trình sẽ mặc định là họ và tên của chủ tài khoản (thông tin khai báo lúc đăng ký tài khoản / tạo bởi admin).')
    slug = models.SlugField(null=True, unique=True, allow_unicode =True, help_text = 'Thông tin này sẽ hiển thị tại địa chỉ web, ví dụ: www.home/duoclieu/XXXXX, với XXXX là thông tin bạn nhập vào')

    def __str__(self):
        return f'{self.tieu_de_chinh}'

    def get_absolute_url(self):
        return reverse('level0-detail', kwargs={'slug': self.slug})

    class Meta:
       verbose_name = 'Tiêu để chính'
       verbose_name_plural = 'C. Tiêu để chính'
       ordering = ['id']
#---------------------
class HinhAnhLv0(models.Model):
    level_0 = models.ForeignKey('Level0', on_delete = models.CASCADE)
    hinh = models.ImageField(upload_to='giaotrinh')
    ten_hinh = models.CharField(max_length = 200)
#---------------------
class Level1(models.Model):
    tieu_de_1 = models.CharField(max_length = 200, verbose_name = 'tiêu đề cấp 1', null=True, blank = True)
    noi_dung = models.TextField(max_length = 5000, verbose_name = 'nội dung', null=True, blank = True)
    level_0 = models.ForeignKey('Level0', on_delete = models.CASCADE, verbose_name = '<-- Tiêu đề chính')
    def __str__(self):
        return f'{self.tieu_de_1}:'

    class Meta:
       verbose_name = 'Tiêu đề cấp 1'
       verbose_name_plural = 'C.1 - Tiêu đề cấp 1'
       ordering = ['id']
#---------------------

duoclieu/views.py
from django.shortcuts import render
from .models import LoiNoiDauDL, HoThucVat, DuocLieu, Level0
#-----------------------------------------------------
def DuocLieuHoc(request):
    """View function for home page of site."""

    So_ho_thuc_vat = HoThucVat.objects.all().count()
    So_duoc_lieu = DuocLieu.objects.all().count()
    So_chuong = Level0.objects.all().count()
    loi_noi_dau = LoiNoiDauDL.objects.all()

    context = {
        'So_ho_thuc_vat': So_ho_thuc_vat,
        'So_duoc_lieu': So_duoc_lieu,
        'So_chuong': So_chuong,
        'loi_noi_dau': loi_noi_dau,
    }
    return render(request, 'duoc_lieu_hoc.html', context=context)

#-----------------------------------------------------
from django.views import generic

class HoThucVatListView (generic.ListView):
    model = HoThucVat
#-----------------------------------------------------
class HoThucVatDetailView(generic.DetailView):
    model = HoThucVat
#-----------------------------------------------------
class DuocLieuListView (generic.ListView):
    model = DuocLieu
#-----------------------------------------------------
from django.contrib.auth.mixins import LoginRequiredMixin

class DuocLieuDetailView(LoginRequiredMixin, generic.DetailView):
    model = DuocLieu
#-----------------------------------------------------
from .models import  Level0, Level1, Level2, Level3, Level4, Level5

class Level0ListView (generic.ListView):
    model = Level0
#-----------------------------------------------------
class Level0DetailView(generic.DetailView):
    model = Level0
#-----------------------------------------------------

#-----------------------------------------------------
#-----------------------------------------------------
#-----------------------------------------------------
#-----------------------------------------------------
#-----------------------------------------------------

duoclieu/templates/duoclieu/duoclieu_detail.html
{% extends "duoc_lieu_hoc.html" %}
{% block style %}

  ol { padding: 0px 0px 0px 0px; }
  ul { padding: 0px 0px 0px 20px; }

{% endblock %}
{% block content %}
<div class="w3-container">
  <div class="w3-right-align">{% if duoclieu.tacdungvacongdung_set.count > 0 %}<small><u>Lần cập nhật gần nhất</u>: {{duoclieu.ngay_dang|date:'d/m/Y (H:i)'}}</small>{% else %}{% endif %}</div>
  <h3 class="w3-center" style="font-family:'Lucida Handwriting'">{{duoclieu.ten_tieng_viet}} <br class="w3-hide-large"><i>(<span class="w3-text-blue">{{duoclieu.ten_la_tinh}}</span>)</i></h3>
  {% if duoclieu.dacdiemvaphanbo_set.count == 0 and duoclieu.bophandung_set.count == 0 and duoclieu.dacdiemviphauvabot_set.count == 0 and duoclieu.tacdungvacongdung_set.count == 0 and duoclieu.thanhphanhoahoc_set.count == 0 and duoclieu.chebien_set.count == 0 and duoclieu.chepham_set.count == 0 and duoclieu.chuy_set.count == 0 and duoclieu.hinhanhminhhoa_set.count == 0 %}
     <p class="w3-center w3-text-red">Chưa cập nhật.</p>
  {% endif %}
  <div style="margin-left:20px;margin-top:20px">
    <ol >
    {% if duoclieu.tenkhoahoc_set.count > 0 %}
      <li><u>Tên khoa học</u>:
        <ul>
          {% for chitiet in duoclieu.tenkhoahoc_set.all %}
          <li class="w3-padding"><i>{{chitiet.ten_latinh_spp}}</i> {% if chitiet.ten_tieng_viet_spp is none %}{% else%}({{chitiet.ten_tieng_viet_spp}}){% endif %}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}

    {% if duoclieu.dacdiemvaphanbo_set.count > 0 %}
      <li><u>Đặc điểm và phân bố</u>:
        <ul>
          {% for chitiet in duoclieu.dacdiemvaphanbo_set.all %}
          <li>{{chitiet.dac_diem_va_phan_bo|safe}}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}

    {% if duoclieu.bophandung_set.count > 0 %}
      <li><u>Bộ phận dùng</u>:
        <ul>
          {% for chitiet in duoclieu.bophandung_set.all %}
          <li>{{chitiet.bo_phan_dung|safe}}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}

    {% if duoclieu.dacdiemviphauvabot_set.count > 0 %}
      <li><u>Đặc điểm vi phẫu và bột</u>:
        <ul>
          {% for chitiet in duoclieu.dacdiemviphauvabot_set.all %}
          <li>{{chitiet.dac_diem_vi_phau_va_bot|safe}}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}

    {% if duoclieu.thanhphanhoahoc_set.count > 0 %}
      <li><u>Thành phần hoá học</u>:
        <ul>
          {% for chitiet in duoclieu.thanhphanhoahoc_set.all %}
          <li>{{chitiet.thanh_phan_hoa_hoc|safe}}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}

    {% if duoclieu.tacdungvacongdung_set.count > 0 %}
      <li><u>Tác dụng và công dụng</u>:
        <ul>
          {% for chitiet in duoclieu.tacdungvacongdung_set.all %}
          <li>{{chitiet.tac_dung_va_cong_dung|safe}}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}

    {% if duoclieu.chebien_set.count > 0 %}
      <li><u>Chế biến</u>:
        <ul>
          {% for chitiet in duoclieu.chebien_set.all %}
          <li>{{chitiet.che_bien|safe}}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}

    {% if duoclieu.chepham_set.count > 0 %}
      <li><u>Chế phẩm</u>:
        <ul>
          {% for chitiet in duoclieu.chepham_set.all %}
          <li>{{chitiet.che_pham|safe}}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}

    {% if duoclieu.chuy_set.count > 0 %}
      <li><u>Chú ý</u>:
        <ul>
          {% for chitiet in duoclieu.chuy_set.all %}
          <li>{{chitiet.chu_y|safe}}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}

    {% if duoclieu.ghichu_set.count > 0 %}
      <li><u>Ghi chú</u>:
        <ul>
          {% for chitiet in duoclieu.ghichu_set.all %}
          <li>{{chitiet.ghi_chu|safe}}</li>
            {% if duoclieu.hinhanhbosung_set.count > 0 %}
            <table>
              <tr>
                <td width=30%><img src="{{duoclieu.hinhanhbosung_set.all.0.hinh_anh_bo_sung.url}}" width="100%"></td>
                <td width=30%><img src="{{duoclieu.hinhanhbosung_set.all.1.hinh_anh_bo_sung.url}}" width="100%"></td>
                <td width=30%><img src="{{duoclieu.hinhanhbosung_set.all.2.hinh_anh_bo_sung.url}}" width="100%"></td>
              </tr>
            </table><br>
            {% endif %}
          {% endfor %}
        </ul>
      </li>
    {% endif %}

      {% if duoclieu.hinhanhminhhoa_set.count > 0 %}
      <li><u>Hình ảnh minh hoạ</u>:<br><br>
        <table class="center1">
          <tr>
            <td class="tb1" width=50%><img src="{{duoclieu.hinhanhminhhoa_set.all.0.hinh_anh_minh_hoa.url}}" width="400px"></td>
            {% if duoclieu.hinhanhminhhoa_set.count > 1 %}
            <td class="tb1"><img src="{{duoclieu.hinhanhminhhoa_set.all.1.hinh_anh_minh_hoa.url}}" width="400px"></td>
            {% endif %}
          </tr>
          {% if duoclieu.hinhanhminhhoa_set.count > 2 %}
          <tr>
            <td class="tb1"><img src="{{duoclieu.hinhanhminhhoa_set.all.2.hinh_anh_minh_hoa.url}}" width="400px"></td>
            {% if duoclieu.hinhanhminhhoa_set.count > 3 %}
            <td class="tb1"><img src="{{duoclieu.hinhanhminhhoa_set.all.3.hinh_anh_minh_hoa.url}}" width="400px"></td>
            {% endif %}
          </tr>
          {% endif %}

          {% if duoclieu.hinhanhminhhoa_set.count > 4 %}
          <tr>
            <td class="tb1"><img src="{{duoclieu.hinhanhminhhoa_set.all.4.hinh_anh_minh_hoa.url}}" width="400px"></td>
            {% if duoclieu.hinhanhminhhoa_set.count > 5 %}
            <td class="tb1"><img src="{{duoclieu.hinhanhminhhoa_set.all.5.hinh_anh_minh_hoa.url}}" width="400px"></td>
            {% endif %}
          </tr>
          {% endif %}

          {% if duoclieu.hinhanhminhhoa_set.count > 6 %}
          <tr>
            <td class="tb1"><img src="{{duoclieu.hinhanhminhhoa_set.all.6.hinh_anh_minh_hoa.url}}" width="400px"></td>
            {% if duoclieu.hinhanhminhhoa_set.count > 7 %}
            <td class="tb1"><img src="{{duoclieu.hinhanhminhhoa_set.all.7.hinh_anh_minh_hoa.url}}" width="400px"></td>
            {% endif %}
          </tr>
          {% endif %}
          {% if duoclieu.hinhanhminhhoa_set.count > 8 %}
          <tr>
            <td class="tb1"><img src="{{duoclieu.hinhanhminhhoa_set.all.8.hinh_anh_minh_hoa.url}}" width="400px"></td>
            {% if duoclieu.hinhanhminhhoa_set.count > 9 %}
            <td class="tb1"><img src="{{duoclieu.hinhanhminhhoa_set.all.9.hinh_anh_minh_hoa.url}}" width="400px"></td>
            {% endif %}
          </tr>
          {% endif %}
        </table>
      </li>
      {% endif %}
    </ol>
  </div>
  {% if duoclieu.nguoi_dang is not none %}
  <div class="w3-right-align">{% if duoclieu.tacdungvacongdung_set.count > 0 %}<small><u>Người đăng</u>: {{duoclieu.nguoi_dang}}</small>{% else %}{% endif %}</div>
  {% endif %}
</div>
{% endblock %}

duoclieu/templates/duoclieu/hothucvat_detail.html
{% extends "duoc_lieu_hoc.html" %}
{% block style %}

  ol { padding: 0px 0px 0px 0px; }
  ul { padding: 0px 0px 0px 20px; }

{% endblock %}
{% block content %}
<div class="w3-container">
  <h3 class="w3-center">Danh sách thực vật trong họ <strong class="w3-text-blue">{{hothucvat.La_tinh}}</strong></h3>
  <div style="margin-left:20px;margin-top:20px">
    <ol>
    {% if hothucvat.duoclieu_set.all.count < 1 %}
    <p class="w3-center w3-text-red">Chưa cập nhật.</p>
    {% else %}
      {% for duoclieu in hothucvat.duoclieu_set.all %}
          <li><a href="{{duoclieu.get_absolute_url}}"><span class="{% if duoclieu.dacdiemvaphanbo_set.count > 1 or duoclieu.hinhanhminhhoa_set.count > 1 %} link {% else %} w3-text-red {% endif %}">{{duoclieu.ten_tieng_viet}}</span> (<i>{{duoclieu.ten_la_tinh}}</i>)</a></li>
          <hr>
      {% endfor %}
    {% endif %}
    </ol>
  </div>
</div>
{% endblock %}

duoclieu/templates/duoclieu/hothucvat_list.html
{% extends "duoc_lieu_hoc.html" %}
{% block content %}
<div class="w3-container">
  <input class="w3-right" id="myInput" type="text" placeholder="Search.."> <br>
  <h3 class="w3-center" style="font-family:'Papyrus'">Danh sách họ thực vật</h3>
  {% if hothucvat_list %}
    <table class="center1" width="95%">
      <tr>
        <th class="tb1 w3-padding w3-light-grey w3-center">Họ Thực vật</th>
        <th class="tb1 w3-padding w3-light-grey w3-center">Thực vật trong họ</th>
      </tr>
    <tbody id="myTable">
    {% for hothucvat in hothucvat_list %}
      <tr>
        <td class="tb1 w3-center w3-padding"><a class="{% if hothucvat.duoclieu_set.count < 1%} w3-text-red {% else %} link {% endif %} w3-padding" href="{{hothucvat.get_absolute_url}}">{{ hothucvat.Tieng_viet|upper }}</a><br>(<strong>{{hothucvat.La_tinh}}</strong>)</td>
        <td class="tb1 w3-padding">
          {% for duoclieu in hothucvat.duoclieu_set.all %}
          <a class="{% if duoclieu.dacdiemvaphanbo_set.count > 0 or duoclieu.tacdungvacongdung_set.count > 0 %} link {% else %} w3-text-red {% endif %}" href="{{duoclieu.get_absolute_url}}">{{duoclieu.ten_tieng_viet}} </a><strong style="font-size: 1.5em">|</strong>
          {% endfor %}</td>
      </tr>
    {% endfor %}
    </tbody>
    </table>
    <br>
  {% else %}
    <p>Chưa cập nhật.</p>
  {% endif %}
</div>
{% endblock %}